## looping 

### for loop

In [1]:
for i in [1,2,3]:
    print(i)

1
2
3


In [74]:
func(6)

36


In [2]:
a=[1,2,3,4,5,6,7,8]

In [3]:
for i in a:
    print(i)

1
2
3
4
5
6
7
8


In [5]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [6]:
a

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
for i in range(len(a)):
    print(i,a[i])

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8


## while loop

In [19]:
i=1
n=5
sum=0
while (i<n):
    sum= sum+i
    print(sum)
    i= i+1

1
3
6
10


In [9]:
count=0
while(count<10):
    print('count is in the loop')
    count= count+1
else:
    print('count is out of the loop')

count is in the loop
count is in the loop
count is in the loop
count is in the loop
count is in the loop
count is in the loop
count is in the loop
count is in the loop
count is in the loop
count is in the loop
count is out of the loop


## if ,elif ,else

In [1]:
x= int(input('Enter the number'))
if (x>10):
    x= x-2
elif (x<10):
    x= x+2
x
    
    

Enter the number2


4

In [3]:
x= int(input('Enter the number'))
if x%2==0:
    print('even')
else:
    print('odd')

Enter the number21
odd


In [4]:
b=20

In [6]:
b==20

True

In [7]:
b!=20

False

In [8]:
b>20

False

In [9]:
b<20

False

In [10]:
a=10
b=20


In [12]:
(a>b) and (b==20)

False

In [13]:
not(True)

False

In [14]:
not(False)

True

In [15]:
not(a==10)

False

In [16]:
a=[1,2,3,4,5,6,7,8]

In [17]:
for x in a:
    if x%2==0:
        print('even')
    else:
        print('odd')

odd
even
odd
even
odd
even
odd
even


In [39]:
a.append(20.5)
a.append('python')
a.remove('python')
a

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 20.5,
 20.5,
 20.5,
 20.5,
 20.5,
 'python',
 20.5,
 'python']

In [40]:
even=[]
odd=[]
float1=[]
string=[]
for x in a:
    if x%2==0:
        even.append(x) 
    elif x%2==1:
        odd.append(x)
    elif x== type(str):
        string.append(x)
    else:
        float1.append(x)
print(even,odd,float1)

TypeError: not all arguments converted during string formatting

In [50]:
a=['2str','45str1']

In [51]:
for i in a:
    print(i)

2str


In [55]:
a

['2str']

In [53]:
var=a[0][0]

In [57]:
b=int(var)

In [56]:
var

'2'

In [58]:
b

2

In [63]:
var1=a[0][1:4]

In [64]:
var1

'str'

In [67]:
## creating the list using input functions

In [71]:
b=[]
count= int(input('Enter the count'))
for i in range(0,count):
    var= int(input('Enter the values'))
    b.append(var)
print(b)
    

Enter the count10
Enter the values1
Enter the values2
Enter the values3
Enter the values4
Enter the values5
Enter the values6
Enter the values7
Enter the values8
Enter the values9
Enter the values9
[1, 2, 3, 4, 5, 6, 7, 8, 9, 9]


In [72]:
def func(x):
    print(x*x)

In [73]:
func(2)

4


In [75]:
def square(x):
    print(x**x)

In [76]:
square(3)

27


In [77]:
def fun(x,y):
    print(x*y)

In [80]:
fun(10,20)

200


In [78]:
def fun(x,y):
    return x*y

In [82]:
fun(2,3)

6

In [83]:
def fun(x=0,y=0):
    return x+y

In [86]:
fun(4)

4

In [104]:
a=[]
even=[]
odd=[]
float1=[]
def fun(a):
    for i in a:
        if i%2==0:
            even.append(i)
        elif i%2==1:
            odd.append(i)
        else:
            float1.append(i)
    print(even,odd,float1)

In [105]:
fun([1,2,3,4,5,10,3.3,8.8])

[2, 4, 10] [1, 3, 5] [3.3, 8.8]


In [106]:
def fact(x):
    if x==1:
        return 1
    else:
        return fact(x-1)*x

In [111]:
fact(3)

6

## filter function

In [119]:
def fun(x):
    if x%2==0:
        return True
    else:
        return False

In [120]:
fun(5)

False

In [121]:
a=[1,2,3,4,5,6,7]

In [122]:
list(filter(fun,a))

[2, 4, 6]

In [137]:
def fun(x):
    return x+2

In [67]:
round(22.44,1)

22.4

In [71]:
num1= float(input('Enter the first number'))
num2= float(input('Enter the second number'))
sum1= num1 + num2
print(round(sum1,3))

Enter the first number22.44444
Enter the second number55.444444
77.889


In [72]:
a=[1,2,3,'a',4,'b','c','d']

In [79]:
def filter1(x,y):
    return [i for i in x if isinstance(i,y)]
nums= filter1(a, int)
strs= filter1(a, str)
print(nums,strs)  

[1, 2, 3, 4] ['a', 'b', 'c', 'd']


In [76]:
isinstance(a,tuple)

False

## Lambda Function

In [80]:
fun= lambda x: x*x

In [81]:
fun(4)

16

In [82]:
fun1= lambda x,y: x**y

In [83]:
fun1(2,3)

8

In [84]:
fun2= lambda x: 'even' if x%2==0 else 'odd'

In [86]:
fun2(3)

'odd'

In [87]:
fun3= lambda x,y: x if x>y else y

In [88]:
fun3(3,4)

4

In [89]:
a=[1,2,3,4,5,6,7]

In [90]:
fun4= lambda x: ['even' if x%2==0 else 'odd' for x in a]

In [91]:
fun4(a)

['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd']

In [92]:
fact= lambda x: 1 if x==1 else fact(x-1)*x

In [94]:
fact(5)

120

## map function

In [95]:
def mult(x):
    return x*x

In [96]:
mult(2)

4

In [100]:
a=[1,2,3,4,5,6]
b=[4,5,6,7]

In [98]:
list(map(mult,a))

[1, 4, 9, 16, 25, 36]

In [101]:
def mult(x,y):
    return x*y

In [102]:
list(map(mult,a,b))

[4, 10, 18, 28]

In [103]:
list(map(lambda x: x**2,b))

[16, 25, 36, 49]

## Numpy

In [9]:
import numpy as np

In [10]:
one_dim= np.array([1,2,3,4,5,6])

In [11]:
one_dim

array([1, 2, 3, 4, 5, 6])

In [12]:
type(one_dim)

numpy.ndarray

In [13]:
one_dim.ndim

1

In [14]:
one_dim.shape

(6,)

In [15]:
one_dim.size

6

In [16]:
one_dim[4]

5

In [17]:
one_dim

array([1, 2, 3, 4, 5, 6])

In [18]:
one_dim[0:4]

array([1, 2, 3, 4])

In [19]:
one_dim[4:6]=[100,200]

In [20]:
one_dim

array([  1,   2,   3,   4, 100, 200])

In [21]:
np.delete(one_dim,4)

array([  1,   2,   3,   4, 200])

In [22]:
one_dim

array([  1,   2,   3,   4, 100, 200])

In [23]:
np.delete(one_dim,(4,5))

array([1, 2, 3, 4])

In [24]:
np.insert(one_dim,2,100)

array([  1,   2, 100,   3,   4, 100, 200])

In [25]:
one_dim= np.arange(0,10).r

In [26]:
one_dim

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
one_dim= np.random.randint(0,10,10)

In [28]:
one_dim

array([8, 2, 9, 2, 1, 3, 6, 1, 5, 6])

In [29]:
one_dim= np.random.rand(10)

In [30]:
one_dim

array([0.79728001, 0.69754448, 0.93643314, 0.06526208, 0.60793088,
       0.19816978, 0.46141631, 0.57416098, 0.46035098, 0.88530259])

## two dimensional Array

In [31]:
two_dim= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
two_dim.ndim

2

In [34]:
two_dim.shape

(3, 3)

In [35]:
two_dim.size

9

In [36]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
two_dim[1,1]

5

In [38]:
two_dim[2,1]

8

In [39]:
two_dim[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
two_dim[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [41]:
two_dim[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [42]:
two_dim[0:3]=[10]

In [43]:
two_dim

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [44]:
two_dim

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [45]:
two_dim[0]=[10]

In [46]:
two_dim

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [47]:
two_dim[:,1]=[10,20,30]

In [48]:
two_dim

array([[10, 10, 10],
       [10, 20, 10],
       [10, 30, 10]])

In [49]:
two_dim= np.arange(0,12).reshape(3,4)

In [50]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
two_dim= np.random.randint(0,20,16).reshape(4,4)

In [52]:
two_dim

array([[ 6,  3, 11,  3],
       [ 2, 15,  3, 11],
       [10, 15,  6, 19],
       [ 3,  3, 13,  5]])

In [53]:
two_dim= np.random.rand(12).reshape(3,4)

In [54]:
two_dim

array([[0.11631707, 0.67875101, 0.1884099 , 0.92377312],
       [0.3942336 , 0.68417545, 0.03404152, 0.84521686],
       [0.99332571, 0.70955881, 0.81704843, 0.24384491]])

In [55]:
## one-dimensional to two-dimensional array

In [56]:
one_dim

array([0.79728001, 0.69754448, 0.93643314, 0.06526208, 0.60793088,
       0.19816978, 0.46141631, 0.57416098, 0.46035098, 0.88530259])

In [57]:
two_dim= one_dim.reshape(2,5, order='C')

In [58]:
two_dim

array([[0.79728001, 0.69754448, 0.93643314, 0.06526208, 0.60793088],
       [0.19816978, 0.46141631, 0.57416098, 0.46035098, 0.88530259]])

In [59]:
two_dim.ndim

2

In [60]:
## two dimensional to one dimensional array

In [61]:
two_dim

array([[0.79728001, 0.69754448, 0.93643314, 0.06526208, 0.60793088],
       [0.19816978, 0.46141631, 0.57416098, 0.46035098, 0.88530259]])

In [62]:
one_dim= np.ravel(two_dim,order='F')

In [63]:
one_dim

array([0.79728001, 0.19816978, 0.69754448, 0.46141631, 0.93643314,
       0.57416098, 0.06526208, 0.46035098, 0.60793088, 0.88530259])

In [64]:
two_dim

array([[0.79728001, 0.69754448, 0.93643314, 0.06526208, 0.60793088],
       [0.19816978, 0.46141631, 0.57416098, 0.46035098, 0.88530259]])

In [67]:
two_dim.reshape(-1,order='F')

array([0.79728001, 0.19816978, 0.69754448, 0.46141631, 0.93643314,
       0.57416098, 0.06526208, 0.46035098, 0.60793088, 0.88530259])

## Artihmetic operatons with matrix

In [72]:
a= np.random.randint(0,10,4).reshape(2,2)

In [73]:
a

array([[7, 6],
       [1, 0]])

In [74]:
b= np.random.randint(0,15,4).reshape(2,2)
b

array([[10, 12],
       [ 7,  8]])

In [75]:
a+b

array([[17, 18],
       [ 8,  8]])

In [76]:
a-b

array([[-3, -6],
       [-6, -8]])

In [77]:
a*b

array([[70, 72],
       [ 7,  0]])

In [78]:
a/b

array([[0.7       , 0.5       ],
       [0.14285714, 0.        ]])

In [80]:
## matrix multiplication
a@b

array([[112, 132],
       [ 10,  12]])

In [83]:
two_dim= np.random.randint(0,12,12).reshape(3,4)
two_dim

array([[ 1,  7, 10, 11],
       [ 4, 11,  3,  1],
       [10, 11,  4,  9]])

In [84]:
np.transpose(two_dim)

array([[ 1,  4, 10],
       [ 7, 11, 11],
       [10,  3,  4],
       [11,  1,  9]])

In [85]:
two_dim

array([[ 1,  7, 10, 11],
       [ 4, 11,  3,  1],
       [10, 11,  4,  9]])

In [86]:
np.mean(two_dim)

6.833333333333333

In [88]:
np.max(two_dim)

11

In [89]:
np.min(two_dim)

1

In [90]:
np.median(two_dim)

8.0

In [94]:
np.sum(two_dim)

82

In [95]:
np.std(two_dim)

3.826080094416332

In [96]:
np.var(two_dim)

14.638888888888888

In [97]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [98]:
a

array([[7, 6],
       [1, 0]])

In [99]:
np.linalg.inv(a)

array([[ 7.93016446e-18,  1.00000000e+00],
       [ 1.66666667e-01, -1.16666667e+00]])

In [101]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [102]:
np.zeros(shape=(2,2))

array([[0., 0.],
       [0., 0.]])

In [103]:
two_dim

array([[ 1,  7, 10, 11],
       [ 4, 11,  3,  1],
       [10, 11,  4,  9]])

In [105]:
two_dim.mean(axis=0)

array([5.        , 9.66666667, 5.66666667, 7.        ])

In [106]:
two_dim.mean(axis=1)

array([7.25, 4.75, 8.5 ])

In [107]:
a

array([[7, 6],
       [1, 0]])

In [108]:
b

array([[10, 12],
       [ 7,  8]])

In [110]:
np.hstack([a,b])

array([[ 7,  6, 10, 12],
       [ 1,  0,  7,  8]])

In [111]:
np.vstack([a,b])

array([[ 7,  6],
       [ 1,  0],
       [10, 12],
       [ 7,  8]])

In [112]:
two_dim

array([[ 1,  7, 10, 11],
       [ 4, 11,  3,  1],
       [10, 11,  4,  9]])

In [118]:
x,y=np.hsplit(two_dim,2)

In [119]:
x

array([[ 1,  7],
       [ 4, 11],
       [10, 11]])

In [116]:
y

array([[10, 11],
       [ 3,  1],
       [ 4,  9]])

In [120]:
np.hsplit(two_dim,[1,2,3])

[array([[ 1],
        [ 4],
        [10]]),
 array([[ 7],
        [11],
        [11]]),
 array([[10],
        [ 3],
        [ 4]]),
 array([[11],
        [ 1],
        [ 9]])]

In [121]:
np.vsplit(two_dim,[1,2])

[array([[ 1,  7, 10, 11]]),
 array([[ 4, 11,  3,  1]]),
 array([[10, 11,  4,  9]])]

In [122]:
two_dim

array([[ 1,  7, 10, 11],
       [ 4, 11,  3,  1],
       [10, 11,  4,  9]])

In [123]:
np.unique(two_dim)

array([ 1,  3,  4,  7,  9, 10, 11])

In [124]:
two_dim

array([[ 1,  7, 10, 11],
       [ 4, 11,  3,  1],
       [10, 11,  4,  9]])

In [125]:
np.delete(two_dim,1,axis=0)

array([[ 1,  7, 10, 11],
       [10, 11,  4,  9]])

In [126]:
np.delete(two_dim,[0,1],axis=0)

array([[10, 11,  4,  9]])

In [127]:
two_dim[:,0]=[1,2,3]

In [128]:
two_dim

array([[ 1,  7, 10, 11],
       [ 2, 11,  3,  1],
       [ 3, 11,  4,  9]])

In [129]:
np.delete(two_dim,[1,3],axis=1)

array([[ 1, 10],
       [ 2,  3],
       [ 3,  4]])

## Three Dimensional Array

In [140]:
three_dim= np.array([[[1,2,10],[3,4,20]],[[5,6,30],[7,8,40]]])

In [141]:
three_dim

array([[[ 1,  2, 10],
        [ 3,  4, 20]],

       [[ 5,  6, 30],
        [ 7,  8, 40]]])

In [142]:
three_dim.ndim

3

In [143]:
three_dim.shape

(2, 2, 3)

In [144]:
three_dim.size

12

In [145]:
three_dim[1,0,0]

5

In [146]:
three_dim[0,0,1]

2

In [155]:
three_dim

array([[[ 1,  2, 10],
        [ 3,  4, 20]],

       [[ 5,  6, 30],
        [ 7,  8, 40]]])

In [163]:
three_dim[[0,1],:,1]

array([[2, 4],
       [6, 8]])

In [166]:
three_dim[1,:,[0,2]]

array([[ 5,  7],
       [30, 40]])

In [168]:
np.delete(three_dim,1,axis=0)

array([[[ 1,  2, 10],
        [ 3,  4, 20]]])

In [169]:
three_dim

array([[[ 1,  2, 10],
        [ 3,  4, 20]],

       [[ 5,  6, 30],
        [ 7,  8, 40]]])

In [170]:
np.delete(three_dim,0,axis=1)

array([[[ 3,  4, 20]],

       [[ 7,  8, 40]]])

In [171]:
np.delete(three_dim,1,axis=2)

array([[[ 1, 10],
        [ 3, 20]],

       [[ 5, 30],
        [ 7, 40]]])