# Input Functions

In [11]:
input('what is your name')

what is your namedeepak


'deepak'

In [12]:
print('my name is deepak')

my name is deepak


In [13]:
a=input('what is your name')
print('my name is :',a)

what is your namedeepak
my name is : deepak


In [14]:
# Adding two numbers

In [15]:
a=int(input('enter the first number'))
b=int(input('enter the second number'))
c=a+b
print('addition of two number is :',c)

enter the first number6
enter the second number4
addition of two number is : 10


# For Loop

In [16]:
for i in [1,2,3]:
    print(i)

1
2
3


In [17]:
a=[1,2,3,4]

In [18]:
for i in a:
    print(i)

1
2
3
4


In [19]:
for i in range(0,10):
    print(i)


0
1
2
3
4
5
6
7
8
9


# While loop

In [20]:
a=1
b=10
c=2
while (a<b):
    print(a)
    a=a+1
    

1
2
3
4
5
6
7
8
9


In [21]:
a=1
b=10
c=2
while (a<b):
    c=c+a
    print(c)
    a=a+1

3
5
8
12
17
23
30
38
47


In [22]:
a=0
while(a<10):
    print('its in the loop')
    a=a+1
else:
    print('out of the loop')

its in the loop
its in the loop
its in the loop
its in the loop
its in the loop
its in the loop
its in the loop
its in the loop
its in the loop
its in the loop
out of the loop


# if,elif,else

In [23]:
x=int(input('enter the number'))
if (x<10):
    print('min number')
elif(x>10):
    print('max number')

enter the number52
max number


In [24]:
x=int(input('enter the number'))
if (x<10):
    x=x+2    
elif(x>10):
    x=x-2
print(x)    
    

enter the number9
11


In [25]:
x=int(input('enter the number '))
if (x%2==0):
    print('even')
else:
    print('odd')

enter the number 6
even


In [26]:
# Finding true or false 

In [27]:
a=10

In [28]:
a==10

True

In [29]:
a<20

True

In [30]:
a>20

False

In [31]:
# !=(not equalto)

In [32]:
a!=20

True

In [33]:
# AND,OR,NOT

In [34]:
a=10
b=20

In [35]:
(a>20) and (b==20)

False

In [36]:
(a>20) or (b==20)

True

In [37]:
not(True)

False

In [38]:
not(False)

True

In [39]:
not(a==10)

False

In [40]:
a=[1,2,3,4,5,6,7,8]

In [41]:
for x in a:
    if(x%2==0):
        print('even')
    else:
        print('odd')

odd
even
odd
even
odd
even
odd
even


In [42]:
even=[]
odd=[]
for x in a:
    if(x%2==0):
        even.append(x)
    else:
        odd.append(x)
print(even,odd)

[2, 4, 6, 8] [1, 3, 5, 7]


In [43]:
a

[1, 2, 3, 4, 5, 6, 7, 8]

In [44]:
a.append(9)
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
a.remove(5)
a

[1, 2, 3, 4, 6, 7, 8, 9]

In [49]:
a=[1,2,3,4,5,20.5,'deepak']

In [50]:
x=[]
y=[]
z=[]
for i in a:
    if i==int:
        x.append(i)
    elif i==float:
        y.append(i)
    else:
        z.append(i)
print(int,float,str)        
        

<class 'int'> <class 'float'> <class 'str'>


In [96]:
## creating the list using input functions

In [102]:
x=[]
a= int(input('Enter the count'))
for i in range(0,a):
    b= int(input('Enter the values'))
    x.append(b)
print(x)

Enter the count10
Enter the values2
Enter the values2
Enter the values2
Enter the values2
Enter the values2
Enter the values2
Enter the values2
Enter the values2
Enter the values2
Enter the values2
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


# Define Functions

In [103]:
def fun(a):
    print(a*a)

In [106]:
fun(20)

400

In [105]:
def fun(a):
    return(a*a)

In [107]:
fun(10)

100

In [108]:
def fun(a):
    return a*a

In [109]:
fun(30)

900

In [110]:
def mul(a):
    return a*a

In [112]:
mul(2)

4

In [113]:
def div(x):
    return x/2
    

In [115]:
div(5)

2.5

In [116]:
def mut(x,y):
    return x+y

In [117]:
mut(20,30)

50

In [171]:
a=[]
even=[]
odd=[]
float1=[]
def fun(a):
    for i in a:
        if i%2==0:
            even.append(i)
        elif i%2==1:
            odd.append(i)
        else:
            float1.append(i)
    print(even,odd,float1)     

In [173]:
fun([1,20.5,2,3,4,5])

[2, 4, 2, 4] [1, 3, 5, 1, 3, 5] [20.5]


In [2]:
# Filter function

In [3]:
def fun(x):
    if x%2==0:
        return True
    else:
        return False
    

In [4]:
fun(2)

True

In [5]:
fun(5)

False

In [6]:
round(22.5)

22

In [14]:
a=float(input('enter the first number'))
b=float(input('enter the second number'))
c=a+b
print(round(c))

enter the first number56.6
enter the second number75.6
132


In [4]:
a=float(input('enter the first number'))
b=float(input('enter the second number'))
c=a+b
print(round(c,2))

enter the first number44
enter the second number55
99.0


In [5]:
a=[1,2,3,'a',4,'b','c','d']

In [84]:
def filter1(x,y):
    return [i for i in x if isinstance(i,y)]
nums= filter1(a, int)
strs= filter1(a, str)
print(nums,strs) 

[1, 2, 3, 4] ['a', 'b', 'c', 'd']


In [85]:
isinstance(a,tuple)

False

# Lamda 

In [21]:
fun= lambda x: x*x

In [22]:
fun(6)

36

In [23]:
fun= lambda x,y: x+y
fun(5,2)

7

In [29]:
fun=lambda x: 'even' if x%2==0 else 'odd'

In [30]:
fun(2)

'even'

In [31]:
fun(5)

'odd'

In [35]:
a=lambda x,y: True if x>y else False

In [36]:
a(5,4)

True

In [37]:
a(2,6)

False

In [46]:
a=[1,2,3,4,5]

In [47]:
fun= lambda  x : ['even' if i%2==0 else 'odd' for i in a]

In [48]:
fun(a)

['odd', 'even', 'odd', 'even', 'odd']

In [73]:
fun= lambda x: 1 if x==1 else fact(x-1)*x

In [74]:
fun(5)

120

# Mapping

In [6]:
def fun(x):
    return x+x

In [7]:
fun(20)

40

In [8]:
a=[1,2,3,4,5,6]

In [9]:
list(map(fun,a))

[2, 4, 6, 8, 10, 12]

In [97]:
a=[1,2,3,4,5,6]
b=[4,5,6,7]

In [98]:
def fun(x,y):
    return x+y

In [99]:
list(map(fun,a,b))

[5, 7, 9, 11]

In [102]:
list(map(lambda x: x*x,a))

[1, 4, 9, 16, 25, 36]

# Numpy - One dimensional Array

In [44]:
import numpy as np

In [45]:
one_dim=np.array([1,2,3,4,5])

In [46]:
type(one_dim)

numpy.ndarray

In [47]:
one_dim.shape

(5,)

In [48]:
one_dim.ndim

1

In [49]:
one_dim.size

5

In [50]:
one_dim[4]

5

In [51]:
one_dim

array([1, 2, 3, 4, 5])

In [52]:
one_dim[0:3]

array([1, 2, 3])

In [53]:
one_dim[1:2]=[100]

In [54]:
one_dim

array([  1, 100,   3,   4,   5])

In [55]:
np.delete(one_dim,3)

array([  1, 100,   3,   5])

In [56]:
np.insert(one_dim,1,200)

array([  1, 200, 100,   3,   4,   5])

In [57]:
one_dim=np.arange(0,10)

In [58]:
one_dim

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
one_dim=np.random.randint(0,10)

In [60]:
one_dim

2

In [61]:
one_dim=np.random.randint(0,10,10)

In [62]:
one_dim

array([8, 3, 1, 5, 2, 6, 2, 6, 2, 5])

In [63]:
one_dim=np.random.rand(15)

In [64]:
one_dim

array([0.44894451, 0.96519164, 0.84443732, 0.34998431, 0.48226651,
       0.36486409, 0.50363736, 0.13695518, 0.3365148 , 0.87907806,
       0.28496838, 0.89840346, 0.27705578, 0.43296615, 0.72999273])

# Two Dimension Array

In [65]:
two_dim= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [66]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
type(two_dim)

numpy.ndarray

In [68]:
two_dim.shape

(3, 3)

In [69]:
two_dim.size

9

In [70]:
two_dim.ndim

2

In [71]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
two_dim[2,2]

9

In [73]:
two_dim[2,1]

8

In [74]:
two_dim[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
two_dim[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [76]:
two_dim[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [77]:
two_dim[0:3]=[10]

In [78]:
two_dim

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [79]:
two_dim[0]=[11]

In [80]:
two_dim

array([[11, 11, 11],
       [10, 10, 10],
       [10, 10, 10]])

In [81]:
two_dim[:,1]=[10,20,30]

In [82]:
two_dim

array([[11, 10, 11],
       [10, 20, 10],
       [10, 30, 10]])

In [83]:
two_dim= np.arange(0,12).reshape(3,4)

In [84]:
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
two_dim= np.random.randint(0,20,9).reshape(3,3)

In [86]:
two_dim

array([[15,  0, 13],
       [ 0, 14,  9],
       [ 4, 10,  1]])

In [87]:
two_dim= np.random.rand(12).reshape(3,4)

In [88]:
two_dim

array([[0.40519852, 0.27390585, 0.9891789 , 0.1117418 ],
       [0.01577373, 0.57069561, 0.81635083, 0.06632528],
       [0.19345016, 0.30449452, 0.13113108, 0.99723591]])

In [89]:
# one dimension into two dimension

In [90]:
one_dim

array([0.44894451, 0.96519164, 0.84443732, 0.34998431, 0.48226651,
       0.36486409, 0.50363736, 0.13695518, 0.3365148 , 0.87907806,
       0.28496838, 0.89840346, 0.27705578, 0.43296615, 0.72999273])

In [91]:
two_dim=one_dim.reshape(3,5, order='c')

In [92]:
two_dim

array([[0.44894451, 0.96519164, 0.84443732, 0.34998431, 0.48226651],
       [0.36486409, 0.50363736, 0.13695518, 0.3365148 , 0.87907806],
       [0.28496838, 0.89840346, 0.27705578, 0.43296615, 0.72999273]])

In [93]:
# Two dimension into one dimension

In [94]:
two_dim

array([[0.44894451, 0.96519164, 0.84443732, 0.34998431, 0.48226651],
       [0.36486409, 0.50363736, 0.13695518, 0.3365148 , 0.87907806],
       [0.28496838, 0.89840346, 0.27705578, 0.43296615, 0.72999273]])

In [95]:
one_dim=two_dim.reshape(-1, order='f')

In [96]:
one_dim

array([0.44894451, 0.36486409, 0.28496838, 0.96519164, 0.50363736,
       0.89840346, 0.84443732, 0.13695518, 0.27705578, 0.34998431,
       0.3365148 , 0.43296615, 0.48226651, 0.87907806, 0.72999273])

In [97]:
two_dim

array([[0.44894451, 0.96519164, 0.84443732, 0.34998431, 0.48226651],
       [0.36486409, 0.50363736, 0.13695518, 0.3365148 , 0.87907806],
       [0.28496838, 0.89840346, 0.27705578, 0.43296615, 0.72999273]])

In [98]:
one_dim=np.ravel(two_dim, order='f')

In [99]:
one_dim

array([0.44894451, 0.36486409, 0.28496838, 0.96519164, 0.50363736,
       0.89840346, 0.84443732, 0.13695518, 0.27705578, 0.34998431,
       0.3365148 , 0.43296615, 0.48226651, 0.87907806, 0.72999273])

# Three dimension array

In [100]:
# Block,rows,columns

In [101]:
three_dim=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,11,12]]])

In [102]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0, 11, 12]]])

In [103]:
three_dim.ndim

3

In [104]:
three_dim.shape

(2, 2, 3)

In [105]:
three_dim.size

12

In [106]:
three_dim[0,1,2]

6

In [107]:
three_dim[1,0,0]

7

In [108]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0, 11, 12]]])

In [109]:
three_dim[0,0]

array([1, 2, 3])

In [110]:
three_dim[0,0,0]

1

In [111]:
three_dim[[1,0]]

array([[[ 7,  8,  9],
        [ 0, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [112]:
three_dim[[0,1],0]
 

array([[1, 2, 3],
       [7, 8, 9]])

In [113]:
three_dim[[0,1],0,2]

array([3, 9])

In [114]:
three_dim[[0,1],:,1]

array([[ 2,  5],
       [ 8, 11]])

In [115]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0, 11, 12]]])

In [116]:
np.delete(three_dim,0,axis=0)

array([[[ 7,  8,  9],
        [ 0, 11, 12]]])

In [117]:
np.delete(three_dim,1,axis=0)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [118]:
np.delete(three_dim,0,axis=1)

array([[[ 4,  5,  6]],

       [[ 0, 11, 12]]])

In [119]:
np.delete(three_dim,1,axis=1)

array([[[1, 2, 3]],

       [[7, 8, 9]]])

In [120]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0, 11, 12]]])

In [121]:
np.delete(three_dim,0,axis=2)

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [122]:
np.delete(three_dim,1,axis=2)

array([[[ 1,  3],
        [ 4,  6]],

       [[ 7,  9],
        [ 0, 12]]])

# Arithmetic operation with Matrix

In [123]:
a=np.random.randint(0,10,8).reshape(4,2)

In [124]:
a

array([[6, 3],
       [1, 2],
       [5, 7],
       [0, 9]])

In [143]:
b=np.random.randint(0,10,12).reshape(3,4)

In [144]:
b

array([[6, 3, 3, 3],
       [8, 2, 3, 5],
       [3, 8, 1, 1]])

In [145]:
a+b

ValueError: operands could not be broadcast together with shapes (4,2) (3,4) 

In [141]:
a-b

ValueError: operands could not be broadcast together with shapes (4,2) (3,4) 

In [142]:
a*b

ValueError: operands could not be broadcast together with shapes (4,2) (3,4) 

In [130]:
a/b

ValueError: operands could not be broadcast together with shapes (4,2) (3,4) 

In [131]:
a

array([[6, 3],
       [1, 2],
       [5, 7],
       [0, 9]])

In [132]:
a.transpose()

array([[6, 1, 5, 0],
       [3, 2, 7, 9]])

In [133]:
b

array([[1, 5, 5, 5],
       [5, 2, 4, 6],
       [1, 9, 1, 6]])

In [134]:
np.transpose(b)

array([[1, 5, 1],
       [5, 2, 9],
       [5, 4, 1],
       [5, 6, 6]])

In [306]:
a.mean()

4.5

In [307]:
np.mean(a)

4.5

In [308]:
np.max(two_dim)

0.9497303461436034

In [309]:
a.max()

9

In [310]:
np.max(a)

9

In [311]:
a.min()

0

In [312]:
np.min(a)

0

In [313]:
a.sum()

54

In [314]:
np.sum(a)

54

In [315]:
a.std()

2.753785273643051

In [316]:
np.std(a)

2.753785273643051

In [324]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [331]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [332]:
np.ones(shape=(4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [333]:
np.ones(shape=(2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [334]:
np.zeros(shape=(2,2))

array([[0., 0.],
       [0., 0.]])

In [335]:
np.zeros(shape=(4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [336]:
np.zeros(shape=(4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [341]:
a

array([[7, 5, 0, 8],
       [7, 4, 4, 4],
       [3, 3, 0, 9]])

In [342]:
a.mean(axis=0)

array([5.66666667, 4.        , 1.33333333, 7.        ])

In [343]:
a.mean(axis=1)

array([5.  , 4.75, 3.75])

In [345]:
a

array([[7, 5, 0, 8],
       [7, 4, 4, 4],
       [3, 3, 0, 9]])

In [346]:
b

array([[6, 8, 8, 6],
       [4, 9, 9, 4],
       [7, 4, 8, 3]])

In [349]:
np.hstack([a,b])

array([[7, 5, 0, 8, 6, 8, 8, 6],
       [7, 4, 4, 4, 4, 9, 9, 4],
       [3, 3, 0, 9, 7, 4, 8, 3]])

In [350]:
np.vstack([a,b])

array([[7, 5, 0, 8],
       [7, 4, 4, 4],
       [3, 3, 0, 9],
       [6, 8, 8, 6],
       [4, 9, 9, 4],
       [7, 4, 8, 3]])

In [352]:
two_dim= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [353]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
np.hsplit(two_dim,[1,2])

[array([[0.44894451],
        [0.36486409],
        [0.28496838]]),
 array([[0.96519164],
        [0.50363736],
        [0.89840346]]),
 array([[0.84443732, 0.34998431, 0.48226651],
        [0.13695518, 0.3365148 , 0.87907806],
        [0.27705578, 0.43296615, 0.72999273]])]

In [369]:
np.vsplit(two_dim,[1,2])

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [370]:
np.hsplit(two_dim,[2,1])

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([], shape=(3, 0), dtype=int32),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

In [376]:
a

array([[7, 5, 0, 8],
       [7, 4, 4, 4],
       [3, 3, 0, 9]])

In [371]:
np.unique(a)

array([0, 3, 4, 5, 7, 8, 9])

In [372]:
np.unique(b)

array([3, 4, 6, 7, 8, 9])

In [375]:
np.unique(three_dim)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12])

In [378]:
np.delete(two_dim,0,axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [379]:
np.delete(two_dim,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])