In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

## z- test

1.	The boys in the class are having mean weight= 9.5kg
Standard deviation=1.1kg
Calculate the percentage(%) of the boys in the following:
1.	Weight less than 8.4kg
2.	Between 7.3kg and 11.7kg
3.	More than 12.8


In [3]:
stats.norm.cdf(8.4,loc=9.5,scale=1.1)

0.15865525393145719

In [4]:
p1=stats.norm.cdf(7.3,loc=9.5,scale=1.1)
p1

0.022750131948179195

In [5]:
p2= stats.norm.cdf(11.7,loc=9.5,scale=1.1)
p2

0.9772498680518208

In [6]:
p2-p1

0.9544997361036416

In [7]:
p= stats.norm.cdf(12.8,loc=9.5,scale=1.1)
p

0.9986501019683699

In [8]:
1-p

0.0013498980316301035

## Central Limit Theorem

2.	Child plays for 2 hours when active with a standard deviation of 0.7hrs . the school class teacher wants to plan a trip with 50 children. As a situation .what is the probability that the children will play for more than 2.2 hours.

In [9]:
import math

In [11]:
s= 0.7/math.sqrt(50)
s

0.09899494936611665

In [13]:
p=stats.norm.cdf(2.2,loc=2,scale=s)
p

0.9783241243695687

In [14]:
1-p

0.021675875630431274

## Central Limit Theorem--Task         
         The average age of marriage is 25 for women and 27 for men in the US. If the standard deviation of women is 4 years, what is the probability that a random selection of 32 women have an average age at marriage between 26 to27?



In [3]:
import math
s=4/math.sqrt(32)
s

0.7071067811865475

In [4]:
p1= stats.norm.cdf(26,loc=25,scale=s)
p1

0.9213503964748575

In [5]:
p2= stats.norm.cdf(27,loc=25,scale=s)
p2

0.9976611325094764

In [7]:
p2-p1

0.07631073603461891

## Z-test with CI

1.	Scores on an exam are normally distributed with a population standard deviation=5.6. a random sample of 40 scores on the exam has a mean of 32.
Estimate the population mean with
a)	80% confidence 
b)	90% confidence
c)	98 confidence


In [8]:
## confidence interval 80%
(32+(1.282*(5.6/math.sqrt(40))))

33.13513118889404

In [9]:
(32-(1.282*(5.6/math.sqrt(40))))

30.864868811105957

In [10]:
## confidence interval 90%

In [11]:
(32+(1.645*(5.6/math.sqrt(40))))

33.45654509027356

In [12]:
(32-(1.645*(5.6/math.sqrt(40))))

30.543454909726446

In [13]:
## confidence interval 98%

In [14]:
(32+(2.326*(5.6/math.sqrt(40))))

34.05952819451446

In [15]:
(32-(2.326*(5.6/math.sqrt(40))))

29.940471805485537

1.	A random sample of 15 observation has a mean of 20 and standard deviation of 3.5. To estimate population mean with 95% confidence level. Find the i) Margin of Error ii) confidence interval.

In [16]:
## Margin of Error

In [17]:
Margin_of_Error= 2.145*(3.5/math.sqrt(15))

In [18]:
Margin_of_Error

1.938428164776812

In [19]:
## Confidence interal

In [20]:
upperlimit= 20+Margin_of_Error
upperlimit

21.938428164776813

In [21]:
lowerlimit= 20-Margin_of_Error
lowerlimit

18.061571835223187

## Task

The average weight of 20 student in a certain school was found to be 165lbs with a standard deviation of 4.5. (a) construct 95% confidence interval for the population mean (b) determine the EBM for population mean.

##  1 tail test

In [24]:
pop_data= stats.norm.rvs(size=100, loc=20, scale=80)

In [26]:
pop_data

array([-154.4797686 ,  -99.72706844,  -63.31290894,  -47.40290723,
        122.13077599,   59.44402723,  136.1300429 ,   86.60307271,
        -19.38434712,  -50.78012537,   71.49790861,  114.96765656,
         10.06793717,  -35.45268789,  -13.08553497,  -28.26476259,
         -0.39374303,  -73.55215828,  -75.7660727 ,   58.77618346,
         85.870059  ,  -50.01586034,  154.19820465,   42.52672946,
         76.9257208 ,  -22.3569104 , -153.41683366,   95.93261854,
         75.21099025,    0.84030495,  -71.70837574,   79.82720948,
        -23.91251852,   48.22073933,   51.27205657,   27.06339224,
         47.8615598 ,   57.15754119,   89.7792513 ,  -75.35562354,
          5.04548857,  102.63379532,  -23.47891969,   99.38766085,
       -170.05324884,  -14.30946153,  -19.10722913,  -51.61977319,
        -12.16238529,   71.03716824,  -98.00883236,  -14.62344766,
         83.08077461,  -96.26956817,   99.88579503,  -62.12103192,
         35.13075939,  126.67459571,   79.44385278,  -64.32047

In [30]:
pop_mean= np.mean(pop_data)
pop_mean

10.551963303536684

In [28]:
sample_data= stats.norm.rvs(size=50, loc=10, scale=60)

In [29]:
sample_data

array([   6.09025895,  -32.4312575 ,  -20.32844725,   82.89022551,
         47.21104273,  102.79385019,  -30.22018386,   69.51326554,
        123.80921355,   18.8047282 ,   70.76524707,   -1.16977335,
        -78.16519484,  -28.67115273,   26.03076774,    8.41651684,
        -10.85533878,  -15.03800687,   -2.21817385,  -59.4615713 ,
       -102.92543986,   28.40086974,  -21.70408738,   18.33112309,
        132.97442369,   59.49578232,   37.99997555,   -9.52656253,
         73.40564978,  -70.10818631,  -44.21759291,  -28.29158997,
         32.41188758,  -42.31299952,   -5.34474087,   49.49784601,
        -18.68035033, -109.58760928,   79.66852275,   44.05801882,
        -26.74395432,    4.25624482,   38.84219529,  -11.03728881,
         42.34725127,   47.81396719,   51.12857096,  -19.66876544,
         99.76157349,  -83.04397252])

In [32]:
stats.ttest_1samp(sample_data,popmean=pop_mean)

TtestResult(statistic=-0.006639283963611017, pvalue=0.9947296141046253, df=49)

## 2 tail test (Independent)

A statistics teacher wants to compare his two classes to see if they performed any differently on the tests he gave that semester. Class A had 25 students with  an average score of 70, standard deviation 15. Class B had 20 students with an average score of 74 , standard deviation 25. Using alpha 0.05 did these two classes perform differently on the tests?.

## t-stats

In [33]:
## sample 1 details: s1= 15, mean= 70, n=25
## sample 2 details: s2=25, mean=74, n=20
total_degree_freedom= (25-1)+(20-1)

In [34]:
total_degree_freedom

43

In [35]:
df1= (25-1)
df1

24

In [36]:
df2= (20-1)
df2

19

In [38]:
s1_squared = 15**2
s1_squared

225

In [39]:
s2_squared= 25**2
s2_squared

625

In [40]:
Sp= ((s1_squared*df1)+ (s2_squared*df2))/total_degree_freedom

In [42]:
Sp

401.74418604651163

In [44]:
tstats= (70-74)/(math.sqrt((Sp**2/25)+ (Sp**2/20)))

In [45]:
tstats

-0.0331886155330439

In [46]:
sample1= stats.norm.rvs(size=25,loc=70,scale=15)

In [47]:
sample1

array([ 62.90337011, 100.89211843,  67.6289383 ,  83.45109719,
        88.5421638 ,  75.92569802,  59.792     ,  59.77851067,
        58.15926011,  76.57617662,  74.53255384,  63.84874582,
        71.54001532,  85.41309033,  65.88620578, 101.87989767,
        52.13916154,  84.39690382,  66.12794422,  68.62814521,
        62.83208771,  86.8570145 ,  60.04560029,  81.03502812,
        50.71753816])

In [48]:
sample2= stats.norm.rvs(size=20,loc=74,scale=25)

In [49]:
sample2

array([102.92852936,  80.88054341, 138.74417221, 103.03140233,
        79.46089887,  89.98386798,  75.90192616,  27.25889693,
        70.66796693,  78.56247053,  33.38484097,  40.36787   ,
        17.6975517 ,  73.0579194 ,  66.0075357 , 116.42193474,
        54.2659676 , 131.37559419,  79.4053789 ,  33.19946982])

In [50]:
stats.ttest_ind(sample1,sample2,equal_var=False)

Ttest_indResult(statistic=-0.2798986579129886, pvalue=0.7819389440634832)

## 2 tail Paired test

A study has conducted to determine the effectiveness of a weight base program. The table below shows the before and after weights of 10 subject in the program. A) Is the program effective for reducing weight? B) (use a 5% significant level) construct a 95% confidence interval and determine the margin of error.

In [53]:
S.NO	Before	After
1	185	169
2	192	187
3	206	193
4	177	176
5	225	194
6	168	171
7	256	228
8	239	217
9	199	204
10	218	195


SyntaxError: invalid syntax (4199083546.py, line 1)